services:
  - type: web
    name: sistema-tickets-api
    env: node
    plan: free
    buildCommand: |
      cd apps/api
      npm install -g pnpm
      pnpm install
      pnpm run build
    startCommand: cd apps/api && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URLS
        value: https://sistema-tickets-web.vercel.app,https://sistema-tickets-web-git-main-ivans-projects-73af2e4f.vercel.app
      - key: JWT_SECRET
        value: pHTuJmXhoBn3UBUCy1OGWaRwWwhPQ2Fe8lf5RinaY5hC90MBiE3XN+niJNkpln0MbPLcJy8DxI9IOLkYkPIWFw==
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        value: "postgresql://postgres:7uffg9a9MwDFN3aU@db.ebuzyebupwpbfcgyfozl.supabase.co:5432/postgres"
      - key: SHADOW_DATABASE_URL
        value: "postgresql://postgres:7uffg9a9MwDFN3aU@db.ebuzyebupwpbfcgyfozl.supabase.co:5432/postgres"
      # OAuth variables (optional - set these if you want OAuth functionality)
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: GOOGLE_CALLBACK_URL
        value: ""

# Database configuration moved to environment variables
# Using Supabase PostgreSQL database
